controllers/OrdersController.php
<?php


namespace app\controllers;


use app\models\Order;
use yii\web\Controller;

class OrdersController extends Controller
{
    public function actionIndex()
    {
        $orders = Order::find()->all();

        return $this->render(
            'index',
            [
                'title' => 'Заказы',
                'orders' => $orders,
            ]
        );
    }
}

controllers/PagesController.php
<?php


namespace app\controllers;


use app\models\Page;
use yii\web\Controller;

class PagesController extends Controller
{
    public function actionIndex()
    {
        $pages = Page::find()->all();

        return $this->render(
            'index',
            [
                'title' => 'Дополнительная информация',
                'pages' => $pages,
            ]
        );
    }

    public function actionView($alias)
    {
        $page = Page::find()->where(['alias' => $alias])->one();
        return $this->render('view', ['page' => $page]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Лысая Собака',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Заказы', 'url' => ['/orders/index']],
            ['label' => 'Информация', 'url' => ['/pages/index']],
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => \app\models\Category::getCategoriesForMenu(),
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Главная', 'url' => ['/site/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Интернет-магазин Лысая Собака (c) <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>